### ISSUE TITLE
Wework listed twice in "companies" dropdown 

### ISSUE THREAD

**Issue by laurakberglund** [laurakberglund/Good-Bytes#85]
During the sign up process, wework is listed twice. If it's for two separate offices, it needs to be noted in this dropdown.

<img width="232" alt="screen shot 2016-03-18 at 12 01 35 am" src="https://cloud.githubusercontent.com/assets/16873520/13868226/f2f925aa-ec9c-11e5-9edf-ab10ac9e7d54.png">

**Comment by laurakberglund** [comment]
Also, @kimmyzouki why do we have a "companies" dropdown list here, when on the next modal they have to choose from a specific list of addresses (which are their company addresses)? Seems confusing and redundant to have both. 

If we just want to know where these people work, then it should just be a field that they fill out themselves for their company name, not have it function as a dropdown menu. Thoughts?

**Comment by nisho5** [comment]
Well, the companies have a defined address, on the first page, they pick the company or they pick Other (if company not listed).

On second page, if the an existing company was selected, the Address is automatically filled. But still they are free to change the address. Or, if "Other" unlisted company was picked, they can pick the address freely.

Also, we don't want to bound the user's address to company address, because sometimes companies might have multiple addresses. as Kimmy explained to me.

Also, the duplicate was removed.
